services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    env_file:
      - ./src/configs/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  scrapy_db:
    build:
      context: src/2025/June/database
      dockerfile: database.dockerfile
    container_name: scrapy_db
    volumes:
      - ./src/2025/June/database/base.py:/database/base.py
      - ./configs/mysql.env:/database/mysql.env
    depends_on:
      - mysql

  bookscraper:
    build:
      context: .
      dockerfile: src/bookscraper/bookscraper.dockerfile
    container_name: bookscraper-container
    volumes:
      - ./src/bookscraper:/app/bookscraper
      - ./src/2025/June/database:/app/src/2025/June/database
      - ./src/configs/scraper.env:/app/configs/scraper.env
      - ./src/configs/mysql.env:/app/src/2025/June/database/mysql.env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - mysql
    working_dir: /app/bookscraper
    entrypoint: [ "scrapy"]
    command: ["crawl", "bookspider", "--loglevel", "INFO"] # can be overwritten from the cli use docker compose run ...

volumes:
  mysql-data: