[tool.black]
line-length = 120
target-version = ['py313']
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |\.json
  |\.md
)/
'''  # Files Black will ignore

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["year"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version"
]